### ISSUE TITLE
Generate status report of RFCs

### ISSUE THREAD

**Issue by domenkozar** [NixOS/rfc-steering-committee#1]
So that it can be added to the agenda of the weekly meeting.

**Comment by domenkozar** [comment]
Status update: I amended open RFCs with shepherd data, two RFCs are unclear of the team status.

Next up is generating simple text report from all the open PRs.

**Comment by worldofpeace** [comment]
The steering committee meetings would also benefit from a recording being made public.

**Comment by lheckemann** [comment]
Fixed by 748653ef91838885e2be62251bba8e47ff785ffc (and following bugfix commits)
