### ISSUE TITLE
When will the next meeting be?

### ISSUE THREAD

**Issue by piegamesde** [NixOS/rfc-steering-committee#111]
Unless there have been meetings which were not documented in this repository (which I don't assume), the last meeting has been two months ago on the 8th of March. This is unfortunate, because the steering committee is an essential part of our process and RFCs end up stalling. RFC 140 had to schedule a meeting with nominated-but-not-appointed shepherds in order to make progress, which is not tragic but still unfortunate. Other RFCs are in need of attention too.

I guess the steering committee will have its reasons, but some communication with the community about the current status would be appreciated.

**Comment by lheckemann** [comment]
Indeed. Various circumstances have prevented us from coming together for a full meeting, but we've provided an update from last week in https://github.com/NixOS/rfc-steering-committee/issues/112. Apologies for the long silence.
