### ISSUE TITLE
Meeting notes are now being posted on Discourse instead

### ISSUE THREAD

**Issue by infinisil** [NixOS/rfc-steering-committee#140]
As per [last week's dicussion](https://discourse.nixos.org/t/rfc-status-summaries/40044) RFCSC meeting summaries will no longer be posted here, check out the [Discourse RFCs category](https://discourse.nixos.org/c/dev/rfc-steering-committee/33) to find them.

**Comment by asymmetric** [comment]
This is now [fixed in the docs](https://github.com/NixOS/rfc-steering-committee/commit/cd2293c1107ee97b459d6f83e0568392254cf18b), can we close?

**Comment by kevincox** [comment]
Yeah, I think we have had this here long enough. Happy to close.
