### ISSUE TITLE
RFC Meeting 2019-10-31

### ISSUE THREAD

**Issue by shlevy** [NixOS/rfc-steering-committee#19]
## General business

- Steering committee elections are coming up

## [Unlabeled RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+no%3Alabel) and [New RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3Astatus%3Anew)

- [RFC 0032 - Phase running changes for better nix-shell use](https://github.com/NixOS/rfcs/pull/32) re-opened by @globin who is taking over

## [RFCs Open for Nominations](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+open+for+nominations%22)

- [RFC 56 - CI all Nix PRs](https://github.com/NixOS/rfcs/pull/56) - Opened for nominations
* [RFC 55 - Retire inactive nixpkgs committers](https://github.com/NixOS/rfcs/pull/55) - Seeking a few further nominations, to follow up next meeting.
* [RFC 54 - https://github.com/NixOS/rfcs/pull/54](https://github.com/NixOS/rfcs/pull/54) - Exploring pulling in the team from NixOS/rfcs#46

## [RFCs in Discussion](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+in+discussion")

* [RFC 17 - Intensional Store](https://github.com/NixOS/rfcs/pull/17): active discussion
* [RFC 40 - "Ret-cont" recursive Nix](https://github.com/NixOS/rfcs/pull/40): updated recently, possibly needs meeting
* [RFC 42 - NixOS Config Options](https://github.com/NixOS/rfcs/pull/42): needs scheduling meeting by @globin 
* [RFC 45 - Deprecating unquoted URL syntax](https://github.com/NixOS/rfcs/pull/45): Eelco to propose FCP
* [RFC 46 - Platform Support Tiers](https://github.com/NixOS/rfcs/pull/46): needs meeting, Ericson2314 is leader, meeting is being set up
* [RFC 49 - Flakes](https://github.com/NixOS/rfcs/pull/49): RFC was simplified
* [RFC 50 - Merge bot for maintainers](https://github.com/NixOS/rfcs/pull/50): Ongoing discussion, FCP after clarifications?

## [RFCs in FCP](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+FCP")

* [RFC 51 - Mark stale nixpkgs issues ](https://github.com/NixOS/rfcs/pull/51): FCP open, ends 2019-11-09

## [Accepted/Rejected](https://github.com/NixOS/rfcs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

* [RFC 41 - SELinux Support](https://github.com/NixOS/rfcs/pull/41): Closed on agreement with author
* [RFC 52 - Away from static ids](https://github.com/NixOS/rfcs/pull/52): Accepted

@Mic92 will lead the next meeting on 2019-11-07.

**Comment by Mic92** [comment]
Sorry. I feel sick today. Could someone else take over the meeting?
Cheers.

**Comment by edolstra** [comment]
I'll be 10 minutes late today, sorry about that.

**Comment by globin** [comment]
RFC #32 opened for nominations
RFC #40 @globin will ping for a meeting
RFC #42 @globin will set up a meeting
RFC #50 @globin will follow-up with author and other shepherds and possibly move to FCP
RFC #51 will be accepted in 2 days

We'll also try and find people who are willing to nominate themselves for the RFCSC, selection is at first meeting in December, i.e. in 4 weeks.

**Comment by domenkozar** [comment]
Who is leading the meeting today, by rotation it's @globin
