### ISSUE TITLE
RFC Meeting 2020-02-06

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/rfc-steering-committee#30]
## [Unlabeled RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+no%3Alabel) and [New RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3Astatus%3A+new)
None

## [RFCs Open for Nominations](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+open+for+nominations%22)

- [RFC 32 - Phase running changes for better nix-shell use](https://github.com/NixOS/rfcs/pull/32)

Shepherds: @Ericson2314 and @lheckemann, need 1 more shepherd.
@lheckemann was going to ask @matthewbauer and @samueldr.

* [RFC 64 - New Documentation Format for nixpkgs and NixOS](https://github.com/NixOS/rfcs/pull/64) - @jtojnar @asymmetric @domenkozar  @alyssais accepted

We forgot to appoint a leader https://github.com/NixOS/rfcs/pull/64#issuecomment-582925610

## [RFCs in Discussion](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+in+discussion")

* [RFC 17 - Intensional Store](https://github.com/NixOS/rfcs/pull/17) - No progress since end of November.
* [RFC 40 - "Ret-cont" recursive Nix](https://github.com/NixOS/rfcs/pull/40) - in discussion
* [RFC 42 - NixOS Config Options](https://github.com/NixOS/rfcs/pull/42) - in discussion
* [RFC 49 - Flakes](https://github.com/NixOS/rfcs/pull/49) - work ongoing
* [RFC 54 - Support levels and tiers](https://github.com/NixOS/rfcs/pull/54) - in discussion
* [RFC 55 - Retire inactive nixpkgs committers](https://github.com/NixOS/rfcs/pull/55) - in discussion
* [RFC 56 - CI all Nix PRs](https://github.com/NixOS/rfcs/pull/56) - in discussion
* [RFC 58 - Named Ellipses](https://github.com/NixOS/rfcs/pull/58) - in discussion
* [RFC 59 - Systemd Service Secrets](https://github.com/NixOS/rfcs/pull/59) - in discussion
* [RFC 62 - Content-addressed paths](https://github.com/NixOS/rfcs/pull/62) - In discussion

## [RFCs in FCP](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+FCP")
None

## [Accepted/Rejected](https://github.com/NixOS/rfcs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

* [RFC 50 Merge bot for maintainers](https://github.com/NixOS/rfcs/pull/50) - Author withdrew RFC https://github.com/NixOS/rfcs/pull/50#issuecomment-581142616

**Comment by worldofpeace** [comment]
Should probably mention who was present during the meeting since this varies:
@edolstra @lheckemann @Mic92 @worldofpeace 

@spacekookie wasn't here today.

**Comment by Mic92** [comment]
@lheckemann will lead the next meeting.
