### ISSUE TITLE
RFC meeting 2020-04-16

### ISSUE THREAD

**Issue by spacekookie** [NixOS/rfc-steering-committee#34]
## [RFCs Open for Nominations](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+open+for+nominations%22)

- [RFC 67 - Common override interface](https://github.com/NixOS/rfcs/pull/67) - try to find shepherds for nominations

## [RFCs in Discussion](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+in+discussion")

* [x] [RFC 17 - Intensional Store](https://github.com/NixOS/rfcs/pull/17) - No updates - pinged leader
* [x] [RFC 32 - Phase running changes for better nix-shell use](https://github.com/NixOS/rfcs/pull/32) - No updates (pinged last meeting)
* [x] [RFC 40 - "Ret-cont" recursive Nix](https://github.com/NixOS/rfcs/pull/40) - No updates (will ping shepherds to assign a new leader)
* [x] [RFC 42 - NixOS Config Options](https://github.com/NixOS/rfcs/pull/42) - No updates (pinged last meeting)
* [x] [RFC 49 - Flakes](https://github.com/NixOS/rfcs/pull/49) - Work in progress
* [x] [RFC 55 - Retire inactive nixpkgs committers](https://github.com/NixOS/rfcs/pull/55) - waiting on worldofpeace's comments. Sorry friends.
* [x] [RFC 58 - Named Ellipses](https://github.com/NixOS/rfcs/pull/58) - Waiting for author response
* [x] [RFC 59 - Systemd Service Secrets](https://github.com/NixOS/rfcs/pull/59) - Work in progress
* [x] [RFC 62 - Content-addressed paths](https://github.com/NixOS/rfcs/pull/62) - No updates/ new meeting was asked for
* [x] [RFC 64 - New Documentation Format for nixpkgs and NixOS](https://github.com/NixOS/rfcs/pull/64) - No updates - pinged leader

## [RFCs in FCP](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+FCP")

None

## [Accepted/Rejected](https://github.com/NixOS/rfcs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

@worldofpeace will lead the next meeting

Future notes: https://pad.mayflower.de/nixos-rfc-steering-committee

**Comment by Mic92** [comment]
For the next meeting we need to find a new shepherd for https://github.com/NixOS/rfcs/pull/42#issuecomment-617024084
and we should talk about https://github.com/NixOS/rfcs/pull/55

**Comment by worldofpeace** [comment]
One thing we should keep in mind when a RFC is moved into discussion is the shepherds and leader need to be filled into the actual RFC document. So we should request that at the same time as commenting it's in discussion.
