### ISSUE TITLE
RFC meeting 2020-04-30

### ISSUE THREAD

**Issue by spacekookie** [NixOS/rfc-steering-committee#36]
## General business

Present in the meeting:  @Mic92, @edolstra, @spacekookie, @lheckemann

## [RFCs Open for Nominations](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+open+for+nominations%22)

* [x] [RFC 67 - Common override interface](https://github.com/NixOS/rfcs/pull/67) - no updates (actually added "open for nomination label")

## [RFCs in Discussion](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+in+discussion")

* [x] [RFC 17 - Intensional Store](https://github.com/NixOS/rfcs/pull/17) - Work ongoing
* [x] [RFC 32 - Phase running changes for better nix-shell use](https://github.com/NixOS/rfcs/pull/32) - globin offered to take over as author, dezgeg was pinged
* [x] [RFC 42 - NixOS Config Options](https://github.com/NixOS/rfcs/pull/42) - No updates
* [x] [RFC 49 - Flakes](https://github.com/NixOS/rfcs/pull/49) - no changes to the RFC, some implementation work
* [x] [RFC 55 - Retire inactive nixpkgs committers](https://github.com/NixOS/rfcs/pull/55) - Will ping author to write down points discussed in the meeting
* [x] [RFC 58 - Named Ellipses](https://github.com/NixOS/rfcs/pull/58) - No updates
* [x] [RFC 59 - Systemd Service Secrets](https://github.com/NixOS/rfcs/pull/59) - No updates
* [x] [RFC 62 - Content-addressed paths](https://github.com/NixOS/rfcs/pull/62) - had meeting last week; implementation progress
* [x] [RFC 64 - New Documentation Format for nixpkgs and NixOS](https://github.com/NixOS/rfcs/pull/64) - active discussion, meeting did happen

## [RFCs in FCP](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+FCP")

None

## [Accepted/Rejected](https://github.com/NixOS/rfcs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

* [x] [RFC 40 - "Ret-cont" recursive Nix](https://github.com/NixOS/rfcs/pull/40): closed by author

## Leader of next meeting

@worldofpeace will lead the next meeting

Future notes: pad.mayflower.de/nixos-rfc-steering-committee

**Comment by Mic92** [comment]
Looks like the RFC meeting committee is falling apart. @worldofpeace was the second time not in the meeting and we had no leader. This time we are also lacking meeting notes.

**Comment by lheckemann** [comment]
I'll prepare and lead the next meeting if @worldofpeace doesn't show up again by then.

**Comment by Mic92** [comment]
I try to contact her.

**Comment by Mic92** [comment]
I still have not heard anything from @worldofpeace. According to https://github.com/NixOS/rfcs/blob/master/rfcs/0043-rfcsc-rotation.md#ending-membership membership would end after two or more regular meetings without an appropriate excuse.
