### ISSUE TITLE
RFC meeting 2020-06-11

### ISSUE THREAD

**Issue by edolstra** [NixOS/rfc-steering-committee#38]
## General business

Present in the meeting: Linus, @edolstra (leading), Mic92, spacekookie

## [Unlabeled RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+no%3Alabel) and [New RFCs](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+new%22+)

* [x] [RFC 68 - Minimal daemon](https://github.com/NixOS/rfcs/pull/68) - open for nominations

## [RFCs Open for Nominations](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A%22status%3A+open+for+nominations%22)

* [x] [RFC 67 - Common override interface](https://github.com/NixOS/rfcs/pull/67) - Nominations: @infinisil. Still seems quite WIP, pending "I will clearly need to extend this but just dumping here some thoughts.". @edolstra and @lheckemann will comment

## [RFCs in Discussion](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+in+discussion")

* [x] [RFC 17 - Intensional Store](https://github.com/NixOS/rfcs/pull/17) - Still in progress, no action required
* [x] [RFC 32 - Phase running changes for better nix-shell use](https://github.com/NixOS/rfcs/pull/32) - @lheckemann will arrange meeting
* [x] [RFC 42 - NixOS settings options](https://github.com/NixOS/rfcs/pull/42) - asked @shlevy to take over
* [x] [RFC 58 - Named Ellipses](https://github.com/NixOS/rfcs/pull/58) - No updates; @edolstra pings
* [x] [RFC 59 - Systemd Service Secrets](https://github.com/NixOS/rfcs/pull/59) - Ongoing; no action required?
* [x] [RFC 62 - Content-addressed paths](https://github.com/NixOS/rfcs/pull/62) - Ongoing

## [RFCs in FCP](https://github.com/NixOS/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3A"status%3A+FCP")

* [x] [RFC 49 - Flakes](https://github.com/NixOS/rfcs/pull/49)

## [Accepted/Rejected](https://github.com/NixOS/rfcs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

None

## Leader of next meeting

@mic92 will lead the next meeting

pad.mayflower.de/nixos-rfc-steering-committee

**Comment by shlevy** [comment]
Why am I being pinged for RFC 42? I haven't been involved in that one.

**Comment by lheckemann** [comment]
@shlevy sorry, it seems we forgot to comment on RFC42 itself, caught up on that in https://github.com/NixOS/rfcs/pull/42#issuecomment-642610991
